ViewModels/DesertsListViewModel.cs
using Site_1.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Site_1.ViewModel
{
    public class DesertsListViewModel
    {
        public IEnumerable<Desert> allDeserts { get; set; }
        public string currCategory { get; set; }
    }
}

ViewModels/HomeViewModel.cs
using Site_1.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Site_1.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Desert> favDeserts { get; set; }
    }
}

ViewModels/ShopCartViewModel.cs
using Site_1.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Site_1.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

Controllers/DesertsController.cs
using Microsoft.AspNetCore.Mvc;
using Site_1.Data.interfaces;
using Site_1.Data.Models;
using Site_1.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Site_1.Controllers
{
    public class DesertsController : Controller
    {
        private readonly IAllDeserts _allDeserts;
        private readonly IDesertsCategory _allCategories;
        public DesertsController(IAllDeserts iAllDeserts, IDesertsCategory iDesertsCat)
        {
            _allDeserts = iAllDeserts;
            _allCategories = iDesertsCat;
               
        }
        [Route("Deserts/List")]
        [Route("Deserts/List/{category}")]
        public ViewResult List(string category)
        {
            IEnumerable<Desert> deserts = null;
            string currСategory = "";
            if (string.IsNullOrEmpty(category))
            {
                deserts = _allDeserts.Deserts.OrderBy(i => i.id);
            }
            else
            {
                if (string.Equals("Пирожные", category, StringComparison.OrdinalIgnoreCase))
                {
                    deserts = _allDeserts.Deserts.Where(i => i.Category.categoryName.Equals("Пирожные")).OrderBy(i => i.id);
                    currСategory = "Пирожные";
                }
                else if (string.Equals("Выпечка", category, StringComparison.OrdinalIgnoreCase))
                {
                    deserts = _allDeserts.Deserts.Where(i => i.Category.categoryName.Equals("Выпечка")).OrderBy(i => i.id);
                    currСategory = "Выпечка";
                }
                else if (string.Equals("Торты", category, StringComparison.OrdinalIgnoreCase))
                {
                    deserts = _allDeserts.Deserts.Where(i => i.Category.categoryName.Equals("Торты")).OrderBy(i => i.id);
                    currСategory = "Торты";
                }
                else if (string.Equals("Пончики", category, StringComparison.OrdinalIgnoreCase))
                {
                    deserts = _allDeserts.Deserts.Where(i => i.Category.categoryName.Equals("Пончики")).OrderBy(i => i.id);
                    currСategory = "Пончики";
                }
            }
            var desertObj = new DesertsListViewModel
            {
                allDeserts = deserts,
                currCategory = currСategory
            };

            ViewBag.title = "Страница о кондитерских изделиях";
            return View(desertObj);
        }
    }

    
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Site_1.Data;
using Site_1.Data.interfaces;
using Site_1.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Site_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllDeserts _desertRep;
        private readonly AppDBContent _db;
        public HomeController(IAllDeserts desertRep, AppDBContent db)
        {
            _desertRep = desertRep;
            _db = db;
        }
        [HttpGet]
        public async Task<IActionResult> Index(string Empsearch)
        {
            ViewData["Getemployeedetails"] = Empsearch;

            var empquery = from x in _db.Desert select x;
            if (!String.IsNullOrEmpty(Empsearch))
            {
                empquery = empquery.Where(x => x.name.Contains(Empsearch) || x.Category.categoryName.Contains(Empsearch));
            }
            var homeDeserts = new HomeViewModel
            {
                favDeserts = await empquery.AsNoTracking().ToListAsync()
            };
            return View(homeDeserts);
        }
        public ViewResult Index()
        {
            var homeDeserts = new HomeViewModel
            {
                favDeserts = _desertRep.getFavDeserts
            };
            return View(homeDeserts);
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Site_1.Data.interfaces;
using Site_1.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Site_1.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allorders;
        private readonly ShopCart shopCart;
        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allorders = allOrders;
            this.shopCart = shopCart;
        }
        public IActionResult CheckOut()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CheckOut(Order order)
        {
            shopCart.listShopItems = shopCart.getShopItems();

            if (shopCart.listShopItems.Count == 0)
            {
                ModelState.AddModelError("", "У вас должны быть товары!");
            }
            if (ModelState.IsValid)
            {
                allorders.createOrder(order);
                return RedirectToAction("Complete");
            }
            return View(order);
        }

        public ViewResult Complete()
        {
            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }
    }
}

Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Site_1.Data.interfaces;
using Site_1.Data.Models;
using Site_1.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Site_1.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllDeserts _desertRep;
        private readonly ShopCart _shopCart;
        //internal object listShopItems;
        public ShopCartController(IAllDeserts desertRep, ShopCart shopCart)
        {
            _desertRep = desertRep;
            _shopCart = shopCart;
        }
        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };
            return View(obj);
        }

        /*internal object getShopItems()
        {
            throw new NotImplementedException();
        }*/
        public RedirectToActionResult addToCart(int id)
        {
            var item = _desertRep.Deserts.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
        //public static implicit operator ShopCartController(ShopCart v)
        //{
       //     throw new NotImplementedException();
       // }
    }
}

Views/Deserts/List.cshtml
<h1>@Model.currCategory</h1>
@*<h3>@ViewBag.Category</h3>*@
<div class="row mt-5 mb-2">
    @{
        foreach (Desert desert in Model.allDeserts)
        {
            @Html.Partial("AllDeserts", desert)
        }
    }

</div>

Views/Home/Index.cshtml
@model HomeViewModel
<div class="row">
    <div class="col-md-12">
        <div class="blog-item blog-post-item">
            <div class="thumb">
                <img src="~/img/tiramisu.jpg" class="img-responsive" width="825" height="383" alt="">
                <div class="blog-contnet">
                    <p>
                        В рецепт классического Тирамису обязательно входят: сливочный сыр Маскарпоне (Mascarpone), куриные яйца, кофе эспрессо, сахар и бисквитное печенье Савоярди (Savoiardi), сверху десерт, как правило, посыпают какао-порошком.
                    </p>
                    <p>
                        Сейчас Тирамису очень популярен во всём мире, но родиной его является Италия. В переводе с итальянского Тирамису значит «Подними меня вверх» или «Вознеси меня» (tira — тяни, mi — меня, su — вверх). Это странное название трактуется по разному, например, что десерт настолько нежный и воздушный, что стоит лишь попробовать — оказываешься в облаках.
                    </p>
                    <p>
                        Часть историков полагает, что тирамису создан в XVII веке в честь великого герцога Козимо III Медичи, но документальных подтверждений этому нет]. Настоящая история этого кондитерского изделия начинается в 1960-х либо в 1970-х годах, что позволяет считать его относительно современным изобретением
                    </p>
                    <p>
                        Письменное упоминание зафиксировано в статье Джузеппе ди Клементе (Giuseppe di Clemente) и датировано 1971 годом. В 1981 году его тёзка Джузеппе Маффиоли (Giuseppe Maffioli) в ежеквартальном журнале «Vin Veneto» писал, что тирамису создал кондитер Роберто Лингуанотто (Roberto Linguanotto) в конце 1960-х годов, «чуть более десятилетия назад», в ресторане «Alle Beccherie» (город Тревизо). Маффиоли подчеркнул, что своим названием тирамису (итал. tira mi sù — буквально «тяни меня вверх», в переносном смысле «подбодри меня») обязан тонизирующим и питательным свойствам его ингредиентов, но никак не свойствам афродизиака.
                    </p>
                    <p>
                        Рецепт также встречается в книге «I dolci del Veneto» (1983 год), затем в более поздних текстах, таких как «Cucina e tradizioni del Veneto», где пишут, что тирамису был создан в послевоенное время в ресторане «Alle Beccherie» шеф-поваром, имевшим опыт работы в Центральной Европе.
                    </p>
                    <p>
                        Наряду с вышеназванными письменными свидетельствами есть легенды, по одной из которых аналогичный десерт был впервые приготовлен в Сиене (Тоскана) специально для Великого герцога Тосканы Козимо III Медичи, однако назывался он «Zuppa del duca».
                    </p>
                    <p>
                        Также есть версии, приписывающие авторство ресторанам «El Toulà» и «Al Fogher». 8 октября 2006 года газета Baltimore Sun опубликовала статью, в которой утверждается, что поставщиком десертов для ресторана «Beccherie» был Карминантонио Яннаконе (Carminantonio Iannaccone), живущий в настоящее время в Балтиморе, штат Мэриленд, США, и что тирамису изобрёл именно он.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row mt-5 mb-2">
    @*{
            foreach (Desert desert in Model.favDeserts)
            {
                @Html.Partial("AllDeserts", desert);
            }
        }*@
</div>
<div>
    <div class="recent-item">
        <div class="recent-post">
            <img src="img/11.jpg" class="img-responsive" width="255" height="120" alt="">
            <a href="https://zira.uz/ru/2018/09/10/na-kogo-podpisatsya-v-instagram-26/" target="_blank">
                <div class="recent-hover"></div>
            </a>
        </div>
        <div class="recent-post">
            <img src="img/22.jpg" class="img-responsive" width="255" height="120" alt="">
            <a href="https://zira.uz/ru/2018/09/10/na-kogo-podpisatsya-v-instagram-26/" target="_blank">
                <div class="recent-hover"></div>
            </a>
        </div>
        <div class="recent-post">
            <img src="img/33.jpg" class="img-responsive" width="255" height="120" alt="">
            <a href="https://zira.uz/ru/2018/09/10/na-kogo-podpisatsya-v-instagram-26/" target="_blank">
                <div class="recent-hover"></div>
            </a>
        </div>
    </div>
</div>

Views/Order/CheckOut.cshtml
@model Order

<div class="row1">
    <h3>Оформление заказа</h3>
    <form asp-action="Checkout" method="post" class="form-check-inline">
        <div class="form-check">
            <label class="btntext" asp-for="name"></label>
            <div class="col111">
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-check">
            <label class="btntext" asp-for="surname"></label>
            <div class="col111">
                <input asp-for="surname" class="form-control" />
                <span asp-validation-for="surname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-check">
            <label class="btntext" asp-for="adress"></label>
            <div class="col111">
                <input asp-for="adress" class="form-control" />
                <span asp-validation-for="adress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-check">
            <label class="btntext" asp-for="phone"></label>
            <div class="col111">
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-check">
            <label class="btntext" asp-for="email"></label>
            <div class="col111">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>
         <input class="btn btn-success" type="submit" value="Завершить заказ" />
    </form>
</div>

Views/Order/Compelete.cshtml
<h3>@ViewBag.Message</h3>

Views/Shared/AllDeserts.cshtml
@model Desert
<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
    <h2> @Model.name</h2>
    <p>@Model.shortDesc</p>
    <p> @Model.price.ToString()</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart"
         asp-action="addToCart" asp-route-id="@Model.id" >Добавить в корзину</a></p>
</div>

Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vojon - HTML5 Responsive Restaurant Template</title>
    <link rel="icon" href="images/favicon.png">
    <link rel="icon" href="images/favicon.png" sizes="57x57">
    <link rel="icon" href="images/favicon.png" sizes="72x72">
    <link rel="icon" href="images/favicon.png" sizes="114x114">
    <link rel="icon" href="images/favicon.png" sizes="144x144">
    <link rel="stylesheet" href="~/css/style.css">
    <link href="#" rel="stylesheet" media="screen" class="skin">

</head>
<body>
    <div class="wrapper">
        <nav class="navigation-section navbar navbar-default bootsnav">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html">vojon</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right" id="top-menu">
                        <li><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" asp-controller="Home" asp-action="Index">Главная</a></li>
                        <li><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" asp-controller="Deserts" asp-action="List" asp-route-category="Торты">Торты</a></li>
                        <li><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" asp-controller="Deserts" asp-action="List" asp-route-category="Выпечка">Выпечка </a></li>
                        <li><a class="u-button-style u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" asp-controller="Deserts" asp-action="List" asp-route-category="Пирожные">Пирожные</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <section class="section blog-title-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="title-contnet">
                            <h2>Delicious desserts</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="section blog-container blog-post" id="blog">
            <div class="container">
                <div class="row">
                    <div class="col-md-9 col-sm-8">
                        <div class="row">
                            @RenderBody()
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-4 sidebar">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="widget">
                                    <div class="search">
                                        <div class="input-group">
                                            <form class="d-flex" method="get" asp-controller="Home" asp-action="Index">
                                                <input value="@ViewData["Getemployeedetails"]" name="Empsearch" class="form-control me-2" type="search" placeholder="Search for ..." aria-label="Search">
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="widget">
                                    <h3 class="headline">КАТЕГОРИИ</h3>
                                    <ul>
                                        <li><a href="https://www.russianfood.com/recipes/bytype/?fid=67" target="_blank"><b>ПУДИНГИ</b>          <span>01</span></a></li>
                                        <li><a href="http://www.busheer.ru/stati/chto-takoe-tort/" target="_blank"><b>ТОРТЫ</b>       <span>02</span></a></li>
                                        <li><a href="https://www.ababilova.com/pechene-eto-ili-istoriya-o-tom-chem-pechen" target="_blank"><b>ПЕЧЕНЬЕ</b>           <span>03</span></a></li>
                                        <li><a href="https://dessertacia.ru/company/articles/1079/" target="_blank"><b>ЧИЗКЕЙК</b>        <span>04</span></a></li>
                                        <li><a href="https://bestsurprise.ru/merengi-i-beze-v-chem-raznica/" target="_blank"><b>МЕРЕНГА</b>        <span>05</span></a></li>
                                        <li><a href="https://volshebnaya-eda.ru/kollekcia-receptov/blanmanzhe/" target="_blank"><b>БЛАНМАНЖЕ</b>           <span>06</span></a></li>
                                        <li><a href="https://art-lunch.ru/recipe/brauni_foto/" target="_blank"><b>БРАУНИ</b>         <span>07</span></a></li>
                                        <li><a href="https://imungu.livejournal.com/43367.html" target="_blank"><b>ВАГАСИ</b>          <span>08</span></a></li>
                                        <li><a href="http://findfood.ru/termin/jokan" target="_blank"><b>ЕКАН</b>   <span>08</span></a></li>
                                        <li><a href="https://www.edimdoma.ru/retsepty/95996-kanele" target="_blank"><b>КАНЕЛЕ</b><span>09</span></a></li>
                                        <li><a href="https://www.gastronom.ru/text/klafuti-s-vishnej-1004438" target="_blank"><b>КЛАФУТИ</b>           <span>10</span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="footer-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 social-item">
                        <div class="top-btn">
                            <a class="top-button " href="#" id="easy-top">
                                <i class="fa fa-angle-up" aria-hidden="true"></i>
                                <i class="fa fa-angle-up" aria-hidden="true"></i>
                            </a>
                        </div>
                        <div class="footer-social-box">
                            <ul>
                                <li><a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="https://twitter.com/?lang=ru" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="https://www.google.ru/" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="https://www.instagram.com/?hl=ru" target="_blank"><i class="fa fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 copyright">
                        <p>Made with <i class="fa fa-heart"></i> by <a href="https://revolthemes.net/" target="_blank">Revolthemes</a>. All Rights Reserved</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
    <script src="js/vendor/jquery-1.12.4.min.js"></script>
    <script src="js/vendor/bootstrap.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/isotope.pkgd.min.js"></script>
    <script src="js/placeholdem.min.js"></script>
    <script src="js/jquery.parallax-1.1.3.js"></script>
    <script src="js/jquery.counterup.min.js"></script>
    <script src="js/waypoints.min.js"></script>
    <script src="js/smoothscroll.min.js"></script>
    <script src="js/bootsnav.js"></script>
    <script src="js/jquery.ajaxchimp.min.js"></script>
    <script src="js/custom.js"></script>
</body>
</html>

Views/ShopCart/Index.cshtml
@model ShopCartViewModel

@foreach (var el in Model.shopCart.listShopItems)
{
    <div class="alert alert-warning mt-3">
         @el.desert.name <br />
         @el.desert.price.ToString("c")
    </div>
}
<hr />
<a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Оплатить</a>